[package]
name = "ahash_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro=true

[dependencies]
ahash = { version = "0.8.11", features = ["std"], default-features = false }
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.100"
